export const HTTP_OK = 200;
export const HTTP_CREATED = 201;
export const HTTP_BAD_REQUEST = 400;
export const HTTP_UNAUTHORIZED = 401;
export const HTTP_NOT_FOUND = 404;
export const HTTP_CONFLICT = 409;
export const HTTP_PAYMENT_REQUIRED = 402;
export const HTTP_ACCEPTED = 202;
export const HTTP_INTERNAL_SERVER_ERROR = 500;
export const HTTP_SERVICE_UNAVAILABLE = 503;

export const HTTP_FORBIDDEN = 403;
export const HTTP_UNPROCESSABLE_ENTITY = 422;

export const HttpStatus = {
  OK: HTTP_OK,
  CREATED: HTTP_CREATED,
  BAD_REQUEST: HTTP_BAD_REQUEST,
  UNAUTHORIZED: HTTP_UNAUTHORIZED,
  FORBIDDEN: HTTP_FORBIDDEN,
  NOT_FOUND: HTTP_NOT_FOUND,
  CONFLICT: HTTP_CONFLICT,
  PAYMENT_REQUIRED: HTTP_PAYMENT_REQUIRED,
  ACCEPTED: HTTP_ACCEPTED,
  UNPROCESSABLE_ENTITY: HTTP_UNPROCESSABLE_ENTITY,
  GONE: 410,
  INTERNAL_SERVER_ERROR: HTTP_INTERNAL_SERVER_ERROR,
  SERVICE_UNAVAILABLE: HTTP_SERVICE_UNAVAILABLE,
} as const;
